package com.devsusana.hometutorpro.core.sue

import com.devsusana.hometutorpro.domain.repository.InferenceRepository
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Adapter bridging the Koog AI Agent framework with MediaPipe LLM Inference.
 * 
 * Koog typically expects a remote `PromptExecutor` that handles HTTP calls to OpenAI/Anthropic.
 * This class intercepts the Koog prompt, formats it for the Gemma 2B instruction-tuned model,
 * and delegates execution to our local `InferenceRepository`.
 */
@Singleton
class MediaPipePromptExecutor @Inject constructor(
    private val inferenceRepository: InferenceRepository
) {
    /**
     * Executes the prompt locally.
     * 
     * @param systemPrompt The system instructions.
     * @param userContext The context gathered from tools and the user's query.
     * @return The text generated by the local LLM.
     */
    suspend fun execute(systemPrompt: String, userContext: String): String {
        val formattedPrompt = formatForGemma(systemPrompt, userContext)
        return inferenceRepository.generateResponse(formattedPrompt)
    }

    /**
     * Formats the prompt using the Gemma instruction tuning template.
     * Gemma uses specific control tokens: <start_of_turn>user, <end_of_turn>, <start_of_turn>model.
     */
    private fun formatForGemma(systemPrompt: String, userContext: String): String {
        return buildString {
            append("<start_of_turn>user\n")
            append(systemPrompt.trimIndent())
            append("\n\n")
            append(userContext.trimIndent())
            append("<end_of_turn>\n")
            append("<start_of_turn>model\n")
        }
    }
}
