import os
import sys
import config

def scaffold_test(file_path):
    if not os.path.exists(file_path):
        print(f"❌ File {file_path} not found.")
        return
        
    if "app/src/main/java/" not in file_path:
        print("ℹ️ Test scaffolding is only supported for production files in 'app/src/main/java/'")
        return

    # Determine test file path by replacing main with test and appending Test
    test_file_path = file_path.replace("app/src/main/java/", "app/src/test/java/").replace(".kt", "Test.kt")
    
    if os.path.exists(test_file_path):
        print(f"ℹ️ Test file already exists at: {test_file_path}")
        return

    print(f"🛠️ Generating unit test scaffold for: {os.path.basename(file_path)}")
    
    with open(file_path, 'r') as f:
        code = f.read()

    prompt = f"""
    Act as a Senior Android QA Engineer.
    Based on the following Kotlin production class, write a complete, compilation-ready Unit Test skeleton using JUnit 5 (or JUnit 4), MockK for mocking dependencies, and Kotlin Coroutines runTest if asynchronous calls are present.
    Follow these strict guidelines:
    - Keep it simple, clean, and compilable.
    - Set up dependencies in a @BeforeEach setup method using mockk() or @MockK.
    - Create at least one dummy test method to serve as a starting point.
    
    PRODUCTION CODE:
    {code}
    
    Return ONLY the raw Kotlin code for the test class. No markdown formatting, no explanation, no backticks (```).
    """

    client = config.get_client()
    try:
        response = config.generate_content_with_retry(client, prompt)
        test_code = response.text.strip()
        
        # Remove markdown code block wrappers if generated by LLM
        if test_code.startswith("```kotlin"):
            test_code = test_code[9:]
        elif test_code.startswith("```"):
            test_code = test_code[3:]
        if test_code.endswith("```"):
            test_code = test_code[:-3]
        test_code = test_code.strip()

        # Create directories if they do not exist
        os.makedirs(os.path.dirname(test_file_path), exist_ok=True)
        
        with open(test_file_path, 'w') as f:
            f.write(test_code)
            
        print(f"✅ Unit test scaffold successfully created at: {test_file_path}")
    except Exception as e:
        print(f"❌ Error generating test: {e}")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        scaffold_test(sys.argv[1])
    else:
        print("Usage: python test_scaffolder.py <path_to_production_file.kt>")
