# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# ============================================================================
# SECURITY: Code Obfuscation and Optimization
# ============================================================================

# Aggressive obfuscation
-repackageclasses 'o'
-allowaccessmodification
-optimizationpasses 5
-overloadaggressively

# Keep line numbers for better crash reports (but obfuscate everything else)
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Remove logging in release builds
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
    public static *** w(...);
    public static *** e(...);
}

# ============================================================================
# SECURITY HARDENING: Ofuscación agresiva de lógica crítica
# ============================================================================

# Renombrar todo lo que no sea estrictamente necesario para Hilt o Room
-keep class com.devsusana.hometutorpro.core.auth.SecureAuthManager { 
    public <init>(...);
}

-keep class com.devsusana.hometutorpro.data.billing.** { 
    public <init>(...);
}

# Evitar que Frida encuentre fácilmente los métodos de validación
-keepclassmembers class * {
    @androidx.annotation.Keep <methods>;
}

# ============================================================================
# Firebase
# ============================================================================

-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses

# Keep data models for Firebase Firestore
-keep class com.devsusana.hometutorpro.data.models.** { *; }
-keep class com.devsusana.hometutorpro.domain.entities.** { *; }

# ============================================================================
# Kotlin Coroutines
# ============================================================================

-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-dontwarn kotlinx.coroutines.**

# ============================================================================
# Jetpack Compose, Hilt, Room, Play Services, and Security Crypto
# ============================================================================
# Handled automatically by bundled library consumer rules.
# R8 is allowed to optimize, shrink, and obfuscate these packages.

-dontwarn androidx.compose.**
-dontwarn com.google.errorprone.annotations.**
-dontwarn com.google.android.gms.**
-dontwarn androidx.room.paging.**
-dontwarn com.google.api.client.http.**
-dontwarn org.joda.time.**

# ============================================================================
# Prevent stripping of native methods
# ============================================================================

-keepclasseswithmembernames class * {
    native <methods>;
}

# ============================================================================
# Keep custom exceptions for better crash reporting
# ============================================================================

-keep public class * extends java.lang.Exception

# ============================================================================
# Kotlin Serialization
# ============================================================================

# Keep serializable classes and their properties
-keepclassmembers class * {
    @kotlinx.serialization.Serializable *;
}
-keepclasseswithmembers class * {
    @kotlinx.serialization.Serializable <fields>;
}

# Keep serializer class generated by the compiler
-keep class *$$serializer { *; }
-keepclassmembers class * {
    *** Companion;
}